name: Marketplace SSL Test 

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  run_build:
    name: Marketplace SSL Test 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Run enable_ssl.sh for marketplace
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OVH_REMOTE_HOST }}
          username: ${{ secrets.OVH_REMOTE_USERNAME }}
          key: ${{ secrets.OVH_SSH_PRIVATE_KEY }}
          port: ${{ secrets.OVH_REMOTE_PORT }}
          script: |
            SECRET_KEY=$(openssl rand -base64 32 | head -c 32)
            sudo sed -i "/^server.jwtServerControlEnabled=/s|.*|server.jwtServerControlEnabled=true|" /usr/local/antmedia/conf/red5.properties
            sudo sed -i "/^server.jwtServerSecretKey=/s|.*|server.jwtServerSecretKey=$SECRET_KEY|" /usr/local/antmedia/conf/red5.properties
            sudo service antmedia restart
            sudo bash /usr/local/antmedia/enable_ssl.sh
      - name: Run enable_ssl.sh for existing domain
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OVH_REMOTE_HOST }}
          username: ${{ secrets.OVH_REMOTE_USERNAME }}
          key: ${{ secrets.OVH_SSH_PRIVATE_KEY }}
          port: ${{ secrets.OVH_REMOTE_PORT }}
          script: |
            sudo bash /usr/local/antmedia/enable_ssl.sh -d ${{ secrets.OVH_REMOTE_HOST }}
